bashrc: move ssh-agent to top of script

diff --git a/home/bashrc b/home/bashrc
--- a/home/bashrc
+++ b/home/bashrc
@@ -424,6 +424,54 @@ echo "Platform:   $METASYSTEM_PLATFORM"
 
 
 #------------------------------------------------------------------------------
+# ssh-agent
+#------------------------------------------------------------------------------
+
+SSH_AGENT_ENV="$HOME/.ssh/agent-env-${HOSTNAME}-${METASYSTEM_OS}-${METASYSTEM_PLATFORM}"
+
+function ssh_agent_pid()
+{
+	if [[ -n ${SSH_AGENT_PID} ]]; then
+		ps -ef | grep $SSH_AGENT_PID | grep ssh-agent$ > /dev/null
+		[[ $? == 0 ]] && echo $SSH_AGENT_PID
+	fi
+}
+
+function ssh_agent_start()
+{
+	echo -n "Starting ssh-agent ... "
+	local pid=$(ssh_agent_pid)
+	if [[ -n $pid ]]; then
+		echo "already active PID $pid"
+	else
+		rm -f ${SSH_AGENT_ENV}
+		ssh-agent | sed 's/^echo/#echo/' > ${SSH_AGENT_ENV}
+		chmod 600 "${SSH_AGENT_ENV}"
+		export SSH_AGENT_PID=
+		. ${SSH_AGENT_ENV} > /dev/null
+		if [[ -n $SSH_AGENT_PID ]]; then
+			echo "PID $SSH_AGENT_PID"
+			ssh-add
+		else
+			echo "failed"
+		fi
+	fi
+}
+
+function ssh_agent_stop()
+{
+	echo "Stopping ssh-agent ..."
+	local pid=$(ssh_agent_pid)
+	[[ -n $pid ]] && kill -9 $pid
+	rm -f ${SSH_AGENT_ENV}
+}
+
+echo
+[[ -f ${SSH_AGENT_ENV} ]] && source ${SSH_AGENT_ENV} > /dev/null
+ssh_agent_start
+
+
+#------------------------------------------------------------------------------
 # dirinfo
 #------------------------------------------------------------------------------
 
@@ -1160,54 +1208,6 @@ alias h=help
 echo -e "\n$_METASYSTEM_RULE"
 echo -e "Type 'help' for a list of metasystem functions and aliases"
 echo -e "$_METASYSTEM_RULE"
-
-
-#------------------------------------------------------------------------------
-# ssh-agent
-#------------------------------------------------------------------------------
-
-#------------------------------------------------------------------------------
-# ssh-agent
-#------------------------------------------------------------------------------
-
-SSH_AGENT_ENV="$HOME/.ssh/agent-env-${HOSTNAME}-${METASYSTEM_OS}-${METASYSTEM_PLATFORM}"
-
-function ssh_agent_start
-{
-     echo -n "Starting ssh-agent ... "
-	 rm -f ${SSH_AGENT_ENV}
-     ssh-agent | sed 's/^echo/#echo/' > ${SSH_AGENT_ENV}
-     chmod 600 "${SSH_AGENT_ENV}"
-	 export SSH_AGENT_PID=
-     . ${SSH_AGENT_ENV} > /dev/null
-	 if [[ -n $SSH_AGENT_PID ]]; then
-		echo "PID $SSH_AGENT_PID"
-		ssh-add
-	 else
-		echo "failed"
-	fi
-}
-
-function ssh_agent_stop()
-{
-	echo "Stopping ssh-agent ..."
-	killall -u $(whoami) ssh-agent
-	for pid in `ps -u $(whoami) | grep ssh-agent | awk '{ print $1 }'`; do
-		echo "PID $pid"
-		kill -9 $pid
-	done
-	rm -f ${SSH_AGENT_ENV}
-}
-
-# Source ssh-agent environment
-if [[ -f ${SSH_AGENT_ENV} ]]; then
-     . ${SSH_AGENT_ENV} > /dev/null
-     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
-         ssh_agent_start;
-     }
-else
-     ssh_agent_start;
-fi
 
 
 #==============================================================================
