Add ssh-agent support

diff --git a/home/bashrc b/home/bashrc
--- a/home/bashrc
+++ b/home/bashrc
@@ -1160,6 +1160,54 @@ echo -e "Type 'help' for a list of metasystem functions and aliases"
 echo -e "$_METASYSTEM_RULE"
 
 
+#------------------------------------------------------------------------------
+# ssh-agent
+#------------------------------------------------------------------------------
+
+#------------------------------------------------------------------------------
+# ssh-agent
+#------------------------------------------------------------------------------
+
+SSH_AGENT_ENV="$HOME/.ssh/agent-env-${HOSTNAME}"
+
+function ssh_agent_start
+{
+     echo -n "Starting ssh-agent ... "
+	 rm -f ${SSH_AGENT_ENV}
+     ssh-agent | sed 's/^echo/#echo/' > ${SSH_AGENT_ENV}
+     chmod 600 "${SSH_AGENT_ENV}"
+	 export SSH_AGENT_PID=
+     . ${SSH_AGENT_ENV} > /dev/null
+	 if [[ -n $SSH_AGENT_PID ]]; then
+		echo "PID $SSH_AGENT_PID"
+		ssh-add
+	 else
+		echo "failed"
+	fi
+}
+
+function ssh_agent_stop()
+{
+	echo "Stopping ssh-agent ..."
+	killall -u $(whoami) ssh-agent
+	for pid in `ps -u $(whoami) | grep ssh-agent | awk '{ print $1 }'`; do
+		echo "PID $pid"
+		kill -9 $pid
+	done
+	rm -f ${SSH_AGENT_ENV}
+}
+
+# Source ssh-agent environment
+if [[ -f ${SSH_AGENT_ENV} ]]; then
+     . ${SSH_AGENT_ENV} > /dev/null
+     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
+         ssh_agent_start;
+     }
+else
+     ssh_agent_start;
+fi
+
+
 #==============================================================================
 # Projects and platforms
 #==============================================================================
