android: add checksum to android-push-binary

diff --git a/home/opt/android b/home/opt/android
--- a/home/opt/android
+++ b/home/opt/android
@@ -268,12 +268,28 @@ function metasystem_android_push_binary()
 {
 	local cmd="adb remount"
 	echo $cmd && $cmd
+	[[ $? != 0 ]] && return $?
+	local ret=0
 	for file in "$@"; do
 		local src=$(metasystem_android_find_binary_local $file)
 		local dst=$(metasystem_android_find_binary_remote $file)
 		cmd="adb push $src $dst"
 		echo $cmd && $cmd
+		[[ $? != 0 ]] && ret=$?
+		local src_sum=$(md5sum $src | awk '{ print $1 }')
+		[[ $? != 0 ]] && ret=$?
+		local dst_sum=$(adb shell "md5sum $dst | awk '{ print \$1 }'" | tr -d '\015')
+		[[ $? != 0 ]] && ret=$?
+		if [[ $src_sum != $dst_sum ]]; then
+			src_sum=$(echo $src_sum | head -c8)
+			dst_sum=$(echo $dst_sum | head -c8)
+			echo "Error: checksum mismatch ($src_sum vs $dst_sum)"
+			ret=1
+		else
+			echo "OK: checksum $src_sum"
+		fi
 	done
+	return $ret
 }
 
 
